---
title: "Forest carbon loss 2001-2020"
subtitle: "Calculated by applying Hansen forest cover loss year to the Woodwell 2000 forest carbon baseline at 30 m resolution"
output:
  word_document:
    reference_docx: style.docx
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, 
                      warning = FALSE, results = FALSE, eval = TRUE)

library(tmap)
# tmap_mode('view')
library(sf)
library(patchwork)
library(segmented)
library(tidyverse)
```

```{r plots}
# Function ----
tidy_forest_loss_df <- function(df) {
  df_carbon <- df %>% 
    st_drop_geometry() %>% 
    dplyr::select(starts_with('carbon_loss'), zone) %>% 
    pivot_longer(-zone, 
                 names_to = 'year',
                 values_to = 'carbon_loss_MgC') %>% 
    mutate(year = str_c(str_extract(year, '\\d{4}'), '-01-01') %>% 
             lubridate::year(), )
  
  df_area <- df %>% 
    st_drop_geometry() %>% 
    dplyr::select(starts_with('forest'), zone) %>% 
    pivot_longer(-zone, 
                 names_to = 'year',
                 values_to = 'forest_loss_ha') %>% 
    mutate(year = str_c(str_extract(year, '\\d{4}'), '-01-01') %>% 
             lubridate::year())
  
  # Join forest carbon and area loss values
  df_join <- df_carbon %>% 
    left_join(df_area)
  
  # df_join %>% 
  #   # mutate(across(carbon_loss_MgC:forest_loss_ha, ~ .x * -1)) %>% 
  #   pivot_longer(cols = carbon_loss_MgC:forest_loss_ha) %>% 
  #   mutate(yr_label = str_c(substr(year-1, 3,4), '-', substr(year, 3,4)))
  
  # Get carbon stock in 2000
  mgc_2000 <- df %>% dplyr::select(zone, sum)
  
  # Get area of each polygon
  mgc_2000$area_ha  <- mgc_2000 %>% 
    st_transform(23836) %>% 
    st_area() %>% 
    units::set_units('ha') %>% 
    units::set_units(NULL)
  
  # Get percent of carbon lost annually and percent of the region deforested 
  df_tidy <- df_join %>% 
    left_join(st_drop_geometry(mgc_2000)) %>% 
    mutate(carbon_loss_pct = carbon_loss_MgC / sum,
           forest_loss_pct = forest_loss_ha / area_ha)

  return(df_tidy)
}

plot_loss <- function(df, title, y_name, facet_scales = 'free_y', 
                      segment =  FALSE,
                      breakpoints = c(), 
                      control = seg.control(display = FALSE)) {
  
  if(segment & is_empty(breakpoints) ) {
    set.seed(12)
    out.lm <- lm(value ~ year, data = df)
    # os <- selgmented(out.lm) ## selects number of breakpoints via the Score test
    os <-selgmented(out.lm, Kmax=3, type="bic") #BIC-based selection

    dat2 = data.frame(x = df$year, y = broken.line(os)$fit)
    df$piecewise <- dat2$y
    
    npsi <- nrow(os$psi)
    segment = npsi > 0
  }
  
  # if(segment & is.vector(breakpoints)) {
  #   o <- segmented(out.lm, seg.Z = ~ year, 
  #                  psi = list(year = breakpoints),
  #                  # control = control)
  #                  control = seg.control(display = FALSE, 
  #                                        fix.npsi = FALSE,
  #                                        K = npsi,
  #                                        # quant = FALSE, 
  #                                        # random = TRUE, 
  #                                        # conv.psi = TRUE
  #                                        ))
  #   dat2 = data.frame(x = df$year, y = broken.line(o)$fit)
  #   df$piecewise <- dat2$y
  # }
  

  p <- df %>% 
    # mutate(mov_avgL = zoo::rollmean(value, 3, align="left", fill=0)) %>%
    # mutate(mov_avgC = zoo::rollmean(value, 3, align="center", fill=0)) %>%
    # mutate(mov_avgR = zoo::rollmean(value, 3, align="right", fill=0)) %>%
    ggplot(aes(x = year, y = value)) +
    geom_point(size = .3, color = 'grey30') +
    geom_line(color = 'grey30', size = .5)
    # geom_line(aes(y = mov_avgL), color = 'steelblue3', size = .5) +
    # geom_line(aes(y = mov_avgC), color = 'tomato3', size = .4) +
    # geom_line(aes(y = mov_avgR), color = 'seagreen4', size = .4) +
  	# geom_hline(yintercept = 0, color = 'grey30', size = 0.4, linetype = 'solid') +
    # geom_smooth(method = 'loess',
    #             se = FALSE,
    #             size = .4,
    #             color= 'steelblue3',
    #             linetype= 'solid',
    #             show.legend = FALSE, 
    #             span = 0.4) +
    
  if(segment) {
    p <- p + geom_line(aes(y = piecewise), color = 'steelblue3', size = .5)
  }
  
  p <- p +
    scale_x_continuous(name = "Year",
                       breaks = 2001:2020,
                       expand = c(0.01, 0.01)) +
  	scale_y_continuous(name = y_name,
  	                   labels = scales::comma) +
    labs(title = title) +
    # facet_grid(rows = vars(zone),
    #            # rows = vars(name), 
    #            scales = facet_scales) +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
      panel.grid.minor = element_blank()) 
  
  return(p)
}


plot_loss_piecewise <- function(df, title, y_name, facet_scales = 'free_y', 
                      segment =  FALSE, 
                      control = seg.control(display = FALSE)) {
  
  if(segment ) {
    set.seed(12)
    out.lm <- lm(value ~ year, data = df)
    # os <- selgmented(out.lm) ## selects number of breakpoints via the Score test
    os <-selgmented(out.lm, Kmax=3, type="bic", control = control) #BIC-based selection

    dat2 = data.frame(x = df$year, y = broken.line(os)$fit)
    df$piecewise <- dat2$y
    
    # npsi <- nrow(os$psi)
    # segment = npsi > 0
  }
  
  # if(segment & is.vector(breakpoints)) {
  #   o <- segmented(out.lm, seg.Z = ~ year, 
  #                  psi = list(year = breakpoints),
  #                  # control = control)
  #                  control = seg.control(display = FALSE, 
  #                                        fix.npsi = FALSE,
  #                                        K = npsi,
  #                                        # quant = FALSE, 
  #                                        # random = TRUE, 
  #                                        # conv.psi = TRUE
  #                                        ))
  #   dat2 = data.frame(x = df$year, y = broken.line(o)$fit)
  #   df$piecewise <- dat2$y
  # }
  
  p <- df %>% 
    ggplot(aes(x = year, y = value)) +
    geom_point(size = .3, color = 'grey30') +
    geom_line(color = 'grey30', size = .5)
    
  if(segment) {
    p <- p + geom_line(aes(y = piecewise), color = 'steelblue3', size = .5)
  }
  
  p <- p +
    scale_x_continuous(name = "Year",
                       breaks = 2001:2020,
                       expand = c(0.01, 0.01)) +
  	scale_y_continuous(name = y_name,
  	                   labels = scales::comma) +
    labs(title = title) +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
      panel.grid.minor = element_blank()) 
  
  return(p)
}
```

```{r}
setwd('/Users/emilysturdivant/PROJECTS/sandbox')

# Gunung Palung ----
site <- 'Gunung Palung'
df <- st_read(here::here('data/gee_exports/GPNP_annual_deforestation.geojson')) %>% 
  summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) %>% 
  mutate(zone = site)

#tm_shape(df) + tm_polygons()

df_tidy <- tidy_forest_loss_df(df)

# Plot 
(pc <- df_tidy %>% 
   rename(value = carbon_loss_MgC) %>%
  plot_loss(title = 'Forest carbon loss', 
            y_name = 'Aboveground carbon (metric tons)', 
            segment = TRUE,
            breakpoints = c(2005, 2010, 2015)))
pf <- df_tidy %>% 
   rename(value = forest_loss_ha) %>% 
  plot_loss(title = 'Forest area loss', 
            y_name = 'Forest area (hectares)')

pc / pf
```

```{r}
# BBBR ----
site <- 'BBBR'
df <- st_read(here::here('data/gee_exports/BBBR_annual_deforestation.geojson')) %>% 
  filter(zone != '')

#tm_shape(df) + tm_polygons()
df_tidy <- tidy_forest_loss_df(df)

df <- df_tidy %>% 
  rename(value = carbon_loss_MgC) %>% 
  filter(str_detect(zone, regex('experiment', ignore_case = TRUE)))
pc1 <- df %>% 
  plot_loss_piecewise(title = 'Experimental', 
            y_name = 'Aboveground carbon (metric tons)',
            facet_scales = 'fixed', 
            segment = TRUE)#c(2017))

df <- df_tidy %>% 
  rename(value = carbon_loss_MgC) %>% 
  filter(str_detect(zone, regex('control 1', ignore_case = TRUE)))
pc2 <- df %>% 
  plot_loss_piecewise(title = 'Control 1', 
            y_name = 'Aboveground carbon (metric tons)',
            facet_scales = 'fixed', 
            segment = TRUE)

df <- df_tidy %>% 
  rename(value = carbon_loss_MgC) %>% 
  filter(str_detect(zone, regex('control 2', ignore_case = TRUE)))
pc3 <- df %>% 
  plot_loss(title = 'Control 2', 
            y_name = 'Aboveground carbon (metric tons)',
            facet_scales = 'fixed', 
            segment = TRUE,
            breakpoints = c(2007, 2012))

pc1 / pc2 / pc3 

# Plot forest carbon and area loss ----
# Plot
pc <- df_tidy %>% 
   rename(value = carbon_loss_MgC) %>% 
  filter(str_detect(zone, regex('experiment', ignore_case = TRUE))) %>% 
  # filter(!str_detect(name, 'forest')) %>%
  plot_loss(title = 'Forest carbon loss', 
            y_name = 'Aboveground carbon (metric tons)',
            facet_scales = 'fixed')
pf <- df_tidy %>% 
   rename(value = forest_loss_ha) %>% 
  # filter(!str_detect(name, 'carbon_loss')) %>%
  plot_loss(title = 'Forest area loss',
            y_name = 'Forest area (hectares)',
            facet_scales = 'fixed')

pc / pf
```

```{r}
# Manombo ----
site <- 'Manombo'
df <- st_read(here::here('data/gee_exports/Manombo_annual_deforestation.geojson')) %>% 
  summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) %>% 
  mutate(zone = site)

df_tidy <- tidy_forest_loss_df(df)

# Plot forest carbon and area loss
pc <- df_tidy %>% 
   rename(value = carbon_loss_MgC) %>%
  plot_loss(title = 'Forest carbon loss', 
            y_name = 'Aboveground carbon (metric tons)')
pf <- df_tidy %>% 
   rename(value = forest_loss_ha) %>% 
  plot_loss(title = 'Forest area loss', 
            y_name = 'Forest area (hectares)')

pc / pf
```

```{r}
# Terra do Meio ----
site <- 'Terra do Meio'
df <- st_read(here::here('data/gee_exports/TdM_annual_deforestation.geojson')) %>% 
  rename(zone = nombre)
# df %>% select(-starts_with('carbon'))

#tm_shape(df) + tm_polygons('type1')

df_tidy <- tidy_forest_loss_df(df) %>% 
  mutate(type = str_extract(zone, '\\w+'))
```

```{r}
# Plot forest carbon and area loss ----
# Plot TIs
pc <- df_tidy %>% 
  filter(type == 'TI') %>% 
   rename(value = carbon_loss_MgC) %>%
  plot_loss(title = 'Forest carbon loss', 
            y_name = 'Aboveground carbon (metric tons)')
pf <- df_tidy %>% 
  filter(type == 'TI') %>% 
   rename(value = forest_loss_ha) %>% 
  plot_loss(title = 'Forest area loss', 
            y_name = 'Forest area (hectares)')

pc
pf
```

```{r}
# Plot RESEX
pc <- df_tidy %>% 
  filter(type == 'RESEX') %>% 
   rename(value = carbon_loss_MgC) %>%
  plot_loss(title = 'Forest carbon loss', 
            y_name = 'Aboveground carbon (metric tons)', 
            facet_scales = 'fixed')
pf <- df_tidy %>% 
  filter(type == 'RESEX') %>% 
   rename(value = forest_loss_ha) %>% 
  plot_loss(title = 'Forest area loss',
            y_name = 'Forest area (hectares)', 
            facet_scales = 'fixed')

pc / pf
```

```{r}
# Plot UCs
pc <- df_tidy %>% 
  filter(type != 'RESEX' & type != 'TI') %>% 
   rename(value = carbon_loss_MgC) %>%
  plot_loss(title = 'Forest carbon loss', 
            y_name = 'Aboveground carbon (metric tons)', 
            facet_scales = 'free_y')
pf <- df_tidy %>% 
  filter(type != 'RESEX' & type != 'TI') %>% 
   rename(value = forest_loss_ha) %>% 
  plot_loss(title = 'Forest area loss', 
            y_name = 'Forest area (hectares)', 
            facet_scales = 'free_y')

pc
pf
```

```{r}
# 
# # Plot
# df_tidy %>% 
#   mutate(carbon_loss_pct = carbon_loss_pct * 100) %>% 
#   ggplot(aes(x = year, y = carbon_loss_pct)) +
#   geom_point(size = 0.4) +
#   geom_line() +
# 	geom_hline(yintercept = 0, color = 'grey30', size = 0.4, linetype = 'dashed') +
#   scale_x_continuous(name = "Year",
#                      breaks = 2001:2020,
#                      ) +
# 	scale_y_continuous(name = 'Aboveground carbon (metric tons)',
# 	                   labels = scales::comma) +
#   labs(title = site,
#        caption = "Annual loss in aboveground carbon storage. Greater values indicate more carbon lost.") +
#   facet_grid(rows = vars(zone),
#              # rows = vars(name), 
#              scales = 'fixed') +
#   theme_minimal() +
#   theme(
#     axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
#     panel.grid.minor = element_blank()) 

# # Plot
# df_tidy %>% 
#   mutate(carbon_loss_pct = carbon_loss_pct * 100) %>% 
#   ggplot(aes(x = year, y = carbon_loss_pct)) +
#   geom_point(size = 0.4) +
#   geom_line() +
# 	geom_hline(yintercept = 0, color = 'grey30', size = 0.4, linetype = 'dashed') +
#   scale_x_continuous(name = "Year",
#                      breaks = 2001:2020,
#                      ) +
# 	scale_y_continuous(name = 'Aboveground carbon (metric tons)',
# 	                   labels = scales::comma) +
#   labs(title = site,
#        caption = "Annual loss in aboveground carbon storage. Greater values indicate more carbon lost.") +
#   facet_grid(rows = vars(zone),
#              # rows = vars(name), 
#              scales = 'fixed') +
#   theme_minimal() +
#   theme(
#     axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1),
#     panel.grid.minor = element_blank()) 
```
