---
title: ""
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo=FALSE, eval = TRUE, message = FALSE)

library(sf)
library(terra)
library(tmap)
library(tidyverse)
```

```{r extract-tropics-prep}
e <- ext(c(xmin = -180, xmax = 180, ymin = -23.5, ymax = 23.5))
bb <- c(e$xmin, e$ymin, e$xmax, e$ymax)
tropics_rect <- st_as_sfc(st_bbox(bb, crs = st_crs(4326)))

tmap_mode('view')
tm_shape(tropics_rect) + tm_borders()

data_dir <- '/Users/emilysturdivant/data'
tropics_rect %>% st_write(file.path(data_dir, 'context', 'tropics_wide.shp'))
```

```{r extract-tropic-countries}
# Select countries where MSF is working ----
standardize_text <- function(x){
  x %>% as.character() %>% 
    str_trim() %>% 
    str_to_upper() %>% 
    stringi::stri_trans_general(str=., id='Latin-ASCII') %>% 
    str_replace_all(' +', ' ') %>% 
    str_replace_all('(, )+', ', ') %>% 
    str_replace_all('( ,)+', ',') %>% 
    str_remove_all('^,') %>% 
    str_trim()
}

# MSF countries
msf_countries <- read_csv(file.path('data', 'MSF_countries.csv'))
msf_countries <- msf_countries %>% 
  mutate(country = standardize_text(country), 
         MSF = 1) %>% 
  arrange(country)

# Load data
countries <- st_read(file.path(data_dir, 'gadm', 'gadm36_0.shp'),
                             promote_to_multi = TRUE) %>% 
  st_cast("POLYGON")

# Simplify and subset countries to those that intersect tropics
countries <- countries %>% st_simplify(dTolerance = 0.001)
countries <- countries[unlist(st_intersects(tropics_rect, countries)),]

# Remove parts of countries <2km2
countries['area'] <- countries %>% st_area()
countries <- countries %>% 
  filter(area > units::set_units(4, 'km^2')) %>% 
  group_by(NAME_0) %>% 
  summarize()

countries <- countries %>% 
  mutate(country = standardize_text(NAME_0)) %>% 
  left_join(msf_countries, by = 'country')

# Save
countries %>% st_write(file.path(data_dir, 'gadm', 'gadm36_0_tropics_simp001big3.shp'))

tm_shape(countries) + tm_polygons(col = 'MSF')
```

```{r extract-tropics-pas}
# Protected area polygons ----
# pa_zip <- file.path(data_dir, 'protected_areas', 'WDPA_Oct2021_Public_shp', 'WDPA_Oct2021_Public_shp.zip')
pa_zips <- list.files(
  file.path(data_dir, 'protected_areas', 'WDPA_Oct2021_Public_shp'),
  pattern = ".zip$", full.names=TRUE, recursive = TRUE)

# Unzip
unzip_and_filter_pa_polygons <- function(z) {
  # z <- pa_zips[[1]]

  # Unzip to temp dir
  miao <- tempfile()
  unzip(z, exdir = miao)
  
  # Load shapefile (polygons)
  (shp_fp <- list.files(miao, pattern = ".shp$", full.names=TRUE, recursive = TRUE))
  pa <- st_read(shp_fp[[2]])
  
  # Filter
  pa <- pa %>% 
    filter(MARINE != 2) %>% 
    st_simplify(dTolerance = 0.001) 
  
  # subset polygons to those that intersect tropics rectangle
  pa_tropics <- pa[unlist(st_intersects(tropics_rect, pa)),]
  
  return(pa_tropics)
}

pa_tropics <- pa_zips %>% purrr::map_dfr(unzip_and_filter_pa_polygons)
pa_tropics %>% 
  st_write(file.path(data_dir, 'protected_areas', 'WDPA_Oct2021_polygons_tropics_simp001.gpkg'))

# Protected area points ----
# pa_zip <- file.path(data_dir, 'protected_areas', 'WDPA_Oct2021_Public_shp', 'WDPA_Oct2021_Public_shp.zip')
pa_zips <- list.files(
  file.path(data_dir, 'protected_areas', 'WDPA_Oct2021_Public_shp'),
  pattern = ".zip$", full.names=TRUE, recursive = TRUE)

# Unzip
unzip_and_filter_pa_points <- function(z) {
  # z <- pa_zips[[1]]

  # Unzip to temp dir
  miao <- tempfile()
  unzip(z, exdir = miao)
  
  # Load shapefile (polygons)
  (shp_fp <- list.files(miao, pattern = "points\\.shp$", full.names=TRUE, recursive = TRUE))
  pa <- st_read(shp_fp[[1]])
  
  pa <- pa[unlist(st_intersects(tropics_rect, pa)),]
  pa <- pa %>% filter(REP_AREA > 0, MARINE != 2)
  pa_buff <- pa %>% st_buffer(8.5*0.001)
  # mutate(buff = st_buffer(sqrt((REP_AREA / pi))))
  # mean(sqrt(pa$REP_AREA / pi))
  
  return(pa_buff)
}

pa_tropics <- pa_zips %>% purrr::map_dfr(unzip_and_filter_pa_points)
pa_tropics %>% 
  st_write(file.path(data_dir, 'protected_areas', 'WDPA_Oct2021_points_tropics_buff0085.gpkg'))

# Merge
pa_polys <- st_read(file.path(data_dir, 'protected_areas', 'WDPA_Oct2021_polygons_tropics_simp001.gpkg'))
pa_tropics2 <- bind_rows(pa_polys, pa_tropics)

pa_tropics2 %>% object.size() %>% print(units = "MB")
pa_tropics2 %>% 
  st_write(file.path(data_dir, 'protected_areas', 'WDPA_Oct2021_tropics_simp001_buff0085.gpkg'))

# OECM polygons ----
# pa_zip <- file.path(data_dir, 'protected_areas', 'WDPA_Oct2021_Public_shp', 'WDPA_Oct2021_Public_shp.zip')
pa_zips <- list.files(
  file.path(data_dir, 'protected_areas', 'WDOECM_Oct2021_Public_shp'),
  pattern = ".zip$", full.names=TRUE, recursive = TRUE)

# Unzip
unzip_and_filter_pas <- function(z) {
  # z <- pa_zips[[1]]

  # Unzip to temp dir
  miao <- tempfile()
  unzip(z, exdir = miao)
  
  # Load shapefile (polygons)
  (shp_fp <- list.files(miao, pattern = "polygons\\.shp$", full.names=TRUE, recursive = TRUE))
  pa <- st_read(shp_fp[[1]])
  
  # Filter
  pa <- pa %>% 
    filter(MARINE != 2) %>% 
    st_simplify(dTolerance = 0.001) 
  
  # subset polygons to those that intersect tropics rectangle
  pa_polys <- pa[unlist(st_intersects(tropics_rect, pa)),]
  
  # Load points
  (shp_fp <- list.files(miao, pattern = "points\\.shp$", full.names=TRUE, recursive = TRUE))
  pa <- st_read(shp_fp[[1]])
  pa <- pa[unlist(st_intersects(tropics_rect, pa)),]
  pa <- pa %>% filter(REP_AREA > 0, MARINE != 2)
  pa_points <- pa %>% st_buffer(8.5*0.001)
  
  # Combine
  pa_tropics <- bind_rows(pa_polys, pa_points)
  
  # Return
  return(pa_tropics)
}

pa_tropics <- pa_zips %>% purrr::map_dfr(unzip_and_filter_pa_polygons)
pa_tropics %>% 
  st_write(file.path(data_dir, 'protected_areas', 'WDOECM_Oct2021_tropics_simp001_buff0085.gpkg'))
```

```{r prep-gsn}
# Global Safety Net ----
gsn_shps <- list.files(
  file.path(data_dir, 'global_safety_net', 'global_safety_net'),
  pattern = ".shp$", full.names=TRUE, recursive = TRUE)

# Unzip
subset_to_tropics <- function(shp_fp) {
  # shp_fp <- gsn_shps[[1]]
  
  # Load data
  pa <- st_read(shp_fp)

  # Filter
  pa <- pa %>% 
    st_simplify(dTolerance = 0.001) 
  
  # subset polygons to those that intersect tropics rectangle
  pa_polys <- pa[unlist(st_intersects(tropics_rect, pa)),]
  
  (fn <- str_split(shp_fp, '/') %>% last() %>% last())
  pa_polys %>% 
    st_write(file.path(data_dir, 'global_safety_net', 'tropics_simp001', 
                       str_c(tools::file_path_sans_ext(fn), '.gpkg')))
}

gsn_shps[[1]] %>% purrr::walk(subset_to_tropics)
```

```{r prep-ifl}
# Intact Forest Landscape ----
in_dir <- file.path(data_dir, 'forests', 'IFL_2016')
out_dir <- file.path(data_dir, 'forests', 'ifl_2016_tropics')
ifl_shp <- list.files(in_dir, pattern = ".shp$", full.names=TRUE, recursive = TRUE)

# Unzip
subset_to_tropics <- function(shp_fp) {
  # shp_fp <- gsn_shps[[1]]
  
  # Load data
  pa <- st_read(shp_fp)

  # Filter
  pa <- pa %>% 
    st_simplify(dTolerance = 0.001) 
  
  # subset polygons to those that intersect tropics rectangle
  pa_polys <- pa[unlist(st_intersects(tropics_rect, pa)),]
  
  (fn <- str_split(shp_fp, '/') %>% last() %>% last())
  pa_polys %>% 
    st_write(out_dir, str_c(tools::file_path_sans_ext(fn), '_simp001.gpkg'))
}

ifl_shp[[1]] %>% purrr::walk(subset_to_tropics)
```

```{r prep-flii}
# FLII ----
out_dir <- file.path(data_dir, 'forests', 'flii_tropics2')
(flii_tifs <- list.files(file.path(data_dir, 'forests', 'flii'), 
                       pattern = 'flii_[^earth].*\\.tif$', 
                       full.names = TRUE))

crop_and_agg <- function(fp) {
  # Get output name
  fn_ac <- file.path(out_dir, str_c(basename(tools::file_path_sans_ext(fp)), '_agg3.tif'))
  
  # Load raster
  r <- terra::rast(fp)
  
  # Get intersection of the bounding boxes of the two rasters 
  # (didn't work with terra::intersect)
  r_bbox <- terra::ext(r) %>% as.vector() %>% sf::st_bbox() %>% sf::st_as_sfc()
  e_bbox <- e %>% as.vector() %>% sf::st_bbox() %>% sf::st_as_sfc()
  bb <- sf::st_intersection(r_bbox, e_bbox)
  if(length(bb) == 0) {
    print('Input raster does not include tropics.')
    return()
    }
  
  bb <- bb %>% sf::st_bbox() %>% as.vector()
  
  # Convert to terra extent object
  bbex <- terra::ext(bb[c(1, 3, 2, 4)])
  
  # Crop
  NAflag(r) <- -9999
  r <- terra::crop(r, bbex)
  
  # Aggregate and save
  terra::aggregate(r, fact = 3, na.rm = TRUE, filename = fn_ac, overwrite = TRUE, 
              datatype = 'INT2U')
}

flii_tifs %>% purrr::walk(crop_and_agg)

# gdalUtils::gdalwarp(srcfile = fp, 
#                     dstfile = fn_ac, 
#                     te = bb, 
#                     tr = c(xres(flii), yres(flii)), 
#                     tap = TRUE, 
#                     overwrite = TRUE)

# Mosaic resulting rasters
in_dir <- file.path(data_dir, 'forests', 'flii_tropics2')
out_dir <- file.path(data_dir, 'forests', 'flii_tropics3')
(flii_tifs <- list.files(in_dir, 
                       pattern = 'flii_[^earth].*\\.tif$', 
                       full.names = TRUE))

gdalUtils::mosaic_rasters(flii_tifs, file.path(out_dir, 'flii_tropics_agg3.tif'))
```

```{r prep-hm}
# Human modification
in_dir <- file.path(data_dir, 'human_influence', 'gHM')
out_dir <- in_dir
(tifs <- list.files(in_dir, pattern = 'gHM\\.tif$', full.names = TRUE))
fp <- tifs[[1]]
  
# Get output name
fn_ac <- file.path(out_dir, str_c(basename(tools::file_path_sans_ext(fp)), '_wgs_tropics.tif'))

# Load raster ----
r <- terra::rast(fp)

# Reproject from Mollweide to WGS84
crs(r)
r_p <- terra::project(r, "epsg:4326")

# Get intersection of the bounding boxes of the two rasters
r_bbox <- terra::ext(r_p) %>% as.vector() %>% sf::st_bbox() %>% sf::st_as_sfc()
e_bbox <- e %>% as.vector() %>% sf::st_bbox() %>% sf::st_as_sfc()
bb <- sf::st_intersection(r_bbox, e_bbox)
if(length(bb) == 0) {
  print('Input raster does not include tropics.')
  return()
  }

# Convert to terra extent object
bb <- bb %>% sf::st_bbox() %>% as.vector()
bbex <- terra::ext(bb[c(1, 3, 2, 4)])

# Crop and save
terra::crop(r_p, bbex, filename = fn_ac, overwrite = TRUE)


```

```{r combine-rasters}
# Load Human modification
hm_fp <- file.path(data_dir, 'human_influence', 'gHM', 'gHM_wgs_tropics.tif')
hm <- terra::rast(fn_ac)

# Load FLII
out_dir <- file.path(data_dir, 'forests', 'flii_tropics3')
flii_fp <- file.path(data_dir, 'forests', 'flii_tropics3', 'flii_tropics_agg3.tif')
flii <- terra::rast(flii_fp)

# Resample to common grid
hm

# Adjust range
flii2 <- flii / 10000


```

```{r plots, echo=FALSE, eval = TRUE, message = FALSE}
# Forest Landscape Integrity Index
flii_dir <- "/Volumes/GoogleDrive/My Drive/3_Biomass_projects/HIH/data/flii"
(flii_tifs <- list.files(flii_dir, '*.tif', full.names = TRUE))

# Load data
flii_africa <- terra::rast(flii_tifs[[1]])
flii_africa <- flii_africa / 1000
summary(flii_africa)
NAflag(flii_africa) <- -9999

plot(flii_africa)

# make test area
library(tmap)
tmap_mode('view')

e <- ext(c(xmin = 22, xmax = 41, ymin = -12, ymax = 2))
bb <- c(e$xmin, e$ymin, e$xmax, e$ymax)

tm_shape(st_as_sfc(st_bbox(bb))) + tm_borders()

flii_sub <- flii_africa %>% crop(e)
plot(flii_sub)

flii_subr <- as(flii_sub, 'Raster')
tm_shape(flii_subr) + tm_raster()

library(mapview)
mapview::mapview(flii_sub)
```